#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = solaris
LDFLAGS = -lnsl -lsocket -L/usr/ucblib -lcurses -lucb -lm

include ../Makefile.common
