#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = solaris
ARCH_FLAGS  = -DSOLARIS  -DCachepages=1024

include ../Makefile.common
