#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = cc
#CFLAGS = -dn

ARCH = solaris
LDFLAGS = -lnsl -lsocket -lcurses -lucb

include ../Makefile.common
