#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC     = cc
#CFLAGS = -dn

ARCH = solaris
LDFLAGS = -lnsl -lsocket -L/usr/ucblib -lcurses -lucb -lm

include ../Makefile.common
