#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = irix62
ARCH_FLAGS  = -DIRIX62

include ../Makefile.common
