#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc

ARCH = solaris
LDFLAGS = -lnsl -lsocket -lcurses  -lucb

include ../Makefile.common
