#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc
CFLAGS = 

ARCH = aix41
LDFLAGS = -lm -lbsd 	# ALWAYS link math lib first!.RE: pow() man page
			# bsd is required for valloc/malloc/...

include ../Makefile.common
