#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

ARCH = aix41
ARCH_FLAGS = -DAIX41
CPPFLAGS = -O2 


include ../Makefile.common
