#*********************************************************
# Platform dependent rules and defines...
#*********************************************************

ARCH = aix41
LDFLAGS = -lbsd -lm

include ../Makefile.common
