#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc
CFLAGS = 

ARCH = aix41
LDFLAGS = -lbsd

include ../Makefile.common
