#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc
CFLAGS = 

ARCH = irix62
LDFLAGS = -lbsd

include ../Makefile.common
