#*********************************************************
#  Platform dependent rules and defines...
#*********************************************************

CC = gcc
CFLAGS =

ARCH = aix41
LDFLAGS = -lm -lbsd

include ../Makefile.common
